// Stanley Shi
// 3/27/21
// TuffyHacks 2021
package hydroponicssimulator;

import java.util.Random;
import javax.swing.*;
import java.util.TimerTask;
import java.util.Timer;
import java.util.concurrent.TimeUnit;

public class HydroponicsSimulatorUI extends javax.swing.JFrame {

    /**
     * Creates new form HydroponicsSimulatorUI
     */
    
    public HydroponicsSimulatorUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        planterPanel = new javax.swing.JPanel();
        planter0 = new javax.swing.JPanel();
        plant0 = new javax.swing.JLabel();
        plantMaturityBar0 = new javax.swing.JProgressBar();
        plantIcon0 = new javax.swing.JLabel();
        harvestButton = new javax.swing.JButton();
        planter1 = new javax.swing.JPanel();
        plant1 = new javax.swing.JLabel();
        plantMaturityBar1 = new javax.swing.JProgressBar();
        plantIcon1 = new javax.swing.JLabel();
        planter2 = new javax.swing.JPanel();
        plant2 = new javax.swing.JLabel();
        plantMaturityBar2 = new javax.swing.JProgressBar();
        plantIcon2 = new javax.swing.JLabel();
        planter3 = new javax.swing.JPanel();
        plant3 = new javax.swing.JLabel();
        plantMaturityBar3 = new javax.swing.JProgressBar();
        plantIcon3 = new javax.swing.JLabel();
        planter4 = new javax.swing.JPanel();
        plant4 = new javax.swing.JLabel();
        plantMaturityBar4 = new javax.swing.JProgressBar();
        plantIcon4 = new javax.swing.JLabel();
        nutrientBarPanel = new javax.swing.JPanel();
        magnesiumBar = new javax.swing.JProgressBar();
        phosphorusBar = new javax.swing.JProgressBar();
        calciumBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        nutrientButtonPanel = new javax.swing.JPanel();
        magnesiumButton = new javax.swing.JButton();
        phosphorusButton = new javax.swing.JButton();
        calciumButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        purchasePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        plantCucumberButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        plantTomatoButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        plantStrawberryButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buyAutoHarvestButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        buyMagnesiumX2Button = new javax.swing.JButton();
        buyPhosphorusX2Button = new javax.swing.JButton();
        buyCalciumX2Button = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        planterPanel.setBackground(new java.awt.Color(153, 255, 255));
        planterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        planterPanel.setName("plantPanel"); // NOI18N

        planter0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        planter0.setName("planter0"); // NOI18N

        plant0.setBackground(new java.awt.Color(204, 255, 255));
        plant0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plant0.setText("Empty");
        plant0.setName("plant0"); // NOI18N

        plantMaturityBar0.setStringPainted(true);

        plantIcon0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plantIcon0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plantIcon0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout planter0Layout = new javax.swing.GroupLayout(planter0);
        planter0.setLayout(planter0Layout);
        planter0Layout.setHorizontalGroup(
            planter0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, planter0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(planter0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plantIcon0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plantMaturityBar0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(plant0, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap())
        );
        planter0Layout.setVerticalGroup(
            planter0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantIcon0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(plantMaturityBar0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        plant0.getAccessibleContext().setAccessibleName("");

        harvestButton.setText("Harvest Mature Plants");
        harvestButton.setActionCommand("");
        harvestButton.setName("harvestButton"); // NOI18N
        harvestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harvestButtonActionPerformed(evt);
            }
        });

        planter1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        planter1.setName("planter1"); // NOI18N

        plant1.setBackground(new java.awt.Color(255, 255, 255));
        plant1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plant1.setText("Empty");
        plant1.setName("plant1"); // NOI18N

        plantMaturityBar1.setStringPainted(true);

        plantIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plantIcon1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plantIcon1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout planter1Layout = new javax.swing.GroupLayout(planter1);
        planter1.setLayout(planter1Layout);
        planter1Layout.setHorizontalGroup(
            planter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(planter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantMaturityBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(plant1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(plantIcon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        planter1Layout.setVerticalGroup(
            planter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(plantMaturityBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        planter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        planter2.setName("planter0"); // NOI18N

        plant2.setBackground(new java.awt.Color(0, 0, 0));
        plant2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plant2.setText("Empty");
        plant2.setName("plant0"); // NOI18N

        plantMaturityBar2.setStringPainted(true);

        plantIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plantIcon2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plantIcon2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout planter2Layout = new javax.swing.GroupLayout(planter2);
        planter2.setLayout(planter2Layout);
        planter2Layout.setHorizontalGroup(
            planter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(planter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantMaturityBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(plant2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(plantIcon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        planter2Layout.setVerticalGroup(
            planter2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(plantMaturityBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        planter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        planter3.setName("planter0"); // NOI18N

        plant3.setBackground(new java.awt.Color(0, 0, 0));
        plant3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plant3.setText("Empty");
        plant3.setName("plant0"); // NOI18N

        plantMaturityBar3.setStringPainted(true);

        plantIcon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plantIcon3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plantIcon3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout planter3Layout = new javax.swing.GroupLayout(planter3);
        planter3.setLayout(planter3Layout);
        planter3Layout.setHorizontalGroup(
            planter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(planter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantMaturityBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(plant3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(plantIcon3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        planter3Layout.setVerticalGroup(
            planter3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(plantMaturityBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        planter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        planter4.setName("planter0"); // NOI18N

        plant4.setBackground(new java.awt.Color(0, 0, 0));
        plant4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plant4.setText("Empty");
        plant4.setName("plant0"); // NOI18N

        plantMaturityBar4.setStringPainted(true);

        plantIcon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plantIcon4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plantIcon4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout planter4Layout = new javax.swing.GroupLayout(planter4);
        planter4.setLayout(planter4Layout);
        planter4Layout.setHorizontalGroup(
            planter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(planter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plantMaturityBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(plant4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(plantIcon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        planter4Layout.setVerticalGroup(
            planter4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planter4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plantIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plant4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(plantMaturityBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout planterPanelLayout = new javax.swing.GroupLayout(planterPanel);
        planterPanel.setLayout(planterPanelLayout);
        planterPanelLayout.setHorizontalGroup(
            planterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(planter0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(planter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(planterPanelLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(harvestButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        planterPanelLayout.setVerticalGroup(
            planterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(planterPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(planterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planter0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(harvestButton)
                .addGap(38, 38, 38))
        );

        nutrientBarPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nutrientBarPanel.setPreferredSize(new java.awt.Dimension(142, 15));

        magnesiumBar.setBackground(new java.awt.Color(255, 255, 255));
        magnesiumBar.setForeground(new java.awt.Color(255, 51, 51));
        magnesiumBar.setToolTipText("");
        magnesiumBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        magnesiumBar.setName("magnesiumBar"); // NOI18N
        magnesiumBar.setPreferredSize(new java.awt.Dimension(140, 15));
        magnesiumBar.setString("Magnesium");
        magnesiumBar.setStringPainted(true);

        phosphorusBar.setBackground(new java.awt.Color(255, 255, 255));
        phosphorusBar.setForeground(new java.awt.Color(51, 204, 0));
        phosphorusBar.setName("magnesiumBar"); // NOI18N
        phosphorusBar.setPreferredSize(new java.awt.Dimension(140, 15));
        phosphorusBar.setString("Phosphorus");
        phosphorusBar.setStringPainted(true);

        calciumBar.setBackground(new java.awt.Color(255, 255, 255));
        calciumBar.setForeground(new java.awt.Color(51, 51, 255));
        calciumBar.setToolTipText("");
        calciumBar.setName("magnesiumBar"); // NOI18N
        calciumBar.setPreferredSize(new java.awt.Dimension(140, 15));
        calciumBar.setString("Calcium");
        calciumBar.setStringPainted(true);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nutrients");

        javax.swing.GroupLayout nutrientBarPanelLayout = new javax.swing.GroupLayout(nutrientBarPanel);
        nutrientBarPanel.setLayout(nutrientBarPanelLayout);
        nutrientBarPanelLayout.setHorizontalGroup(
            nutrientBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(magnesiumBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(phosphorusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
            .addComponent(calciumBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nutrientBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        nutrientBarPanelLayout.setVerticalGroup(
            nutrientBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nutrientBarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(magnesiumBar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phosphorusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calciumBar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nutrientButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        magnesiumButton.setBackground(new java.awt.Color(255, 51, 51));
        magnesiumButton.setForeground(new java.awt.Color(255, 255, 255));
        magnesiumButton.setText("Magnesium");
        magnesiumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magnesiumButtonActionPerformed(evt);
            }
        });

        phosphorusButton.setBackground(new java.awt.Color(51, 204, 0));
        phosphorusButton.setForeground(new java.awt.Color(255, 255, 255));
        phosphorusButton.setText("Phosphorus");
        phosphorusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phosphorusButtonActionPerformed(evt);
            }
        });

        calciumButton.setBackground(new java.awt.Color(51, 51, 255));
        calciumButton.setForeground(new java.awt.Color(255, 255, 255));
        calciumButton.setText("Calcium");
        calciumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calciumButtonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Nutrients");

        javax.swing.GroupLayout nutrientButtonPanelLayout = new javax.swing.GroupLayout(nutrientButtonPanel);
        nutrientButtonPanel.setLayout(nutrientButtonPanelLayout);
        nutrientButtonPanelLayout.setHorizontalGroup(
            nutrientButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nutrientButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nutrientButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(nutrientButtonPanelLayout.createSequentialGroup()
                        .addComponent(magnesiumButton)
                        .addGap(18, 18, 18)
                        .addComponent(phosphorusButton)
                        .addGap(18, 18, 18)
                        .addComponent(calciumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nutrientButtonPanelLayout.setVerticalGroup(
            nutrientButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nutrientButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(nutrientButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(magnesiumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phosphorusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calciumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        purchasePanel.setBackground(new java.awt.Color(102, 255, 102));
        purchasePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Purchase and Plant Seeds");

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Cucumber");

        plantCucumberButton.setText("Plant");
        plantCucumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantCucumberButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Harvests for $2");

        jLabel7.setText("$1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plantCucumberButton))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(plantCucumberButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Tomato");

        jLabel8.setText("$5");

        plantTomatoButton.setText("Plant");
        plantTomatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantTomatoButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Harvest for $15");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plantTomatoButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(plantTomatoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Strawberry");

        plantStrawberryButton.setText("Plant");
        plantStrawberryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantStrawberryButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Harvest for $40");

        jLabel9.setText("$10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plantStrawberryButton)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plantStrawberryButton)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout purchasePanelLayout = new javax.swing.GroupLayout(purchasePanel);
        purchasePanel.setLayout(purchasePanelLayout);
        purchasePanelLayout.setHorizontalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        purchasePanelLayout.setVerticalGroup(
            purchasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        moneyLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        moneyLabel.setText("$25");

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Upgrades");

        jLabel14.setText("Auto Harvest");

        buyAutoHarvestButton.setText("Buy");
        buyAutoHarvestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAutoHarvestButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("$300");

        jLabel16.setText("Magnesium x2");

        jLabel17.setText("Phosphorus x2");

        jLabel18.setText("Calcium x2");

        buyMagnesiumX2Button.setText("Buy");
        buyMagnesiumX2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyMagnesiumX2ButtonActionPerformed(evt);
            }
        });

        buyPhosphorusX2Button.setText("Buy");
        buyPhosphorusX2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyPhosphorusX2ButtonActionPerformed(evt);
            }
        });

        buyCalciumX2Button.setText("Buy");
        buyCalciumX2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyCalciumX2ButtonActionPerformed(evt);
            }
        });

        jLabel19.setText("$100");

        jLabel20.setText("$100");

        jLabel21.setText("$100");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buyAutoHarvestButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buyCalciumX2Button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buyMagnesiumX2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buyPhosphorusX2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(buyMagnesiumX2Button)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(buyPhosphorusX2Button)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(buyCalciumX2Button)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(buyAutoHarvestButton)
                    .addComponent(jLabel15))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nutrientBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(planterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nutrientButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(purchasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(moneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(moneyLabel)
                            .addGap(18, 18, 18)
                            .addComponent(purchasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(nutrientBarPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(planterPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nutrientButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void magnesiumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magnesiumButtonActionPerformed
        magnesiumBar.setValue(magnesiumBar.getValue() + addMagnesium);
    }//GEN-LAST:event_magnesiumButtonActionPerformed

    private void calciumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calciumButtonActionPerformed
        calciumBar.setValue(calciumBar.getValue() + addCalcium);
    }//GEN-LAST:event_calciumButtonActionPerformed

    private void harvestPlants(){
        JLabel[] plantList = {plant0, plant1, plant2, plant3, plant4}; //List of plants
        JLabel[] iconList = {plantIcon0, plantIcon1, plantIcon2, plantIcon3, plantIcon4}; 
        JProgressBar[] maturityList = {plantMaturityBar0, plantMaturityBar1, plantMaturityBar2, plantMaturityBar3, plantMaturityBar4};
        for(int i = 0; i < maturityList.length; i++){
            if(maturityList[i].getValue() == 100){
                maturityList[i].setValue(0);
                if(plantList[i].getText() == "Cucumber"){
                    money += 2;
                }
                else if (plantList[i].getText() == "Tomato"){
                    money += 15;
                }
                else if (plantList[i].getText() == "Strawberry"){
                    money += 40;
                }
                updateMoneyLabel();
                plantList[i].setText("Empty");
                iconList[i].setIcon(null);
            }
        }
    }
    
    private void harvestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harvestButtonActionPerformed
        harvestPlants();
    }//GEN-LAST:event_harvestButtonActionPerformed

    private void plantCucumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantCucumberButtonActionPerformed
        JLabel[] plantList = {plant0, plant1, plant2, plant3, plant4}; //List of plants
        JLabel[] iconList = {plantIcon0, plantIcon1, plantIcon2, plantIcon3, plantIcon4}; 
        if(money >= 1){
            for(int i = 0; i < plantList.length; i++){
            //Plants this vegetable into the first empty planter
                if(plantList[i].getText().equals("Empty")){
                    plantList[i].setText("Cucumber");
                    iconList[i].setIcon(stage1Icon);
                    money -= 1;
                    updateMoneyLabel();
                    break;  //Break out of for loop after planting our plant
                }
            }
        }
    }//GEN-LAST:event_plantCucumberButtonActionPerformed

    private void phosphorusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phosphorusButtonActionPerformed
        phosphorusBar.setValue(phosphorusBar.getValue() + addPhosphorus);
    }//GEN-LAST:event_phosphorusButtonActionPerformed

    private void plantTomatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantTomatoButtonActionPerformed
        JLabel[] plantList = {plant0, plant1, plant2, plant3, plant4}; //List of plants
        JLabel[] iconList = {plantIcon0, plantIcon1, plantIcon2, plantIcon3, plantIcon4}; 
        if(money >= 5){
            for(int i = 0; i < plantList.length; i++){
            //Plants this vegetable into the first empty planter
                if(plantList[i].getText().equals("Empty")){
                    plantList[i].setText("Tomato");
                    iconList[i].setIcon(stage1Icon);
                    money -= 5;
                    updateMoneyLabel();
                    break;  //Break out of for loop after planting our plant
                }
            }
        }
    }//GEN-LAST:event_plantTomatoButtonActionPerformed

    private void plantStrawberryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantStrawberryButtonActionPerformed
        JLabel[] plantList = {plant0, plant1, plant2, plant3, plant4}; //List of plants
        JLabel[] iconList = {plantIcon0, plantIcon1, plantIcon2, plantIcon3, plantIcon4}; 
        if(money >= 10){
            for(int i = 0; i < plantList.length; i++){
            //Plants this vegetable into the first empty planter
                if(plantList[i].getText().equals("Empty")){
                    plantList[i].setText("Strawberry");
                    iconList[i].setIcon(stage1Icon);
                    money -= 10;
                    updateMoneyLabel();
                    break;  //Break out of for loop after planting our plant
                }
            }
        }
    }//GEN-LAST:event_plantStrawberryButtonActionPerformed

    private void buyAutoHarvestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAutoHarvestButtonActionPerformed
        if(money >= 300){
            autoHarvest = true;
            buyAutoHarvestButton.setEnabled(false);
            harvestButton.setEnabled(false);
            money -= 300;
            updateMoneyLabel();
        }
    }//GEN-LAST:event_buyAutoHarvestButtonActionPerformed

    private void buyMagnesiumX2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyMagnesiumX2ButtonActionPerformed
        if(money >= 100){
            addMagnesium *= 2;
            buyMagnesiumX2Button.setEnabled(false);
            money -= 100;
            updateMoneyLabel();
        }
    }//GEN-LAST:event_buyMagnesiumX2ButtonActionPerformed

    private void buyPhosphorusX2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPhosphorusX2ButtonActionPerformed
        if(money >= 100){
            addPhosphorus *= 2;
            buyPhosphorusX2Button.setEnabled(false);
            money -= 100;
            updateMoneyLabel();
        }
    }//GEN-LAST:event_buyPhosphorusX2ButtonActionPerformed

    private void buyCalciumX2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyCalciumX2ButtonActionPerformed
        if(money >= 100){
            addCalcium *= 2;
            buyCalciumX2Button.setEnabled(false);
            money -= 100;
            updateMoneyLabel();
        }
    }//GEN-LAST:event_buyCalciumX2ButtonActionPerformed

    private void tick(){
        JLabel[] plantList = {plant0, plant1, plant2, plant3, plant4}; //List of plants
        JLabel[] iconList = {plantIcon0, plantIcon1, plantIcon2, plantIcon3, plantIcon4}; 
        JProgressBar[] maturityList = {plantMaturityBar0, plantMaturityBar1, plantMaturityBar2, plantMaturityBar3, plantMaturityBar4};
        Random rand = new Random();
        
        for(int i = 0; i < plantList.length; i++){
            if(!plantList[i].getText().equals("Empty")){
                
                //Consumes nutrients to increase maturity
                if(maturityList[i].getValue() < 100){
                    if(magnesiumBar.getValue() > 0 && phosphorusBar.getValue() > 0 && calciumBar.getValue() > 0){
                        magnesiumBar.setValue(magnesiumBar.getValue() - 1);
                        phosphorusBar.setValue(phosphorusBar.getValue() - 1);
                        calciumBar.setValue(calciumBar.getValue() - 1);
                        maturityList[i].setValue(maturityList[i].getValue() + rand.nextInt(4 - 2 + 1) + 2);
                    }
                }
                
                //Update icons based on maturaty
                if(maturityList[i].getValue() == 100){
                    iconList[i].setIcon(stage3Icon);
                }
                else if(maturityList[i].getValue() >= 50){
                    iconList[i].setIcon(stage2Icon);
                }
                
                //Harvest plants if auto harvest upgrade is bought
                if(autoHarvest){
                    harvestPlants();
                }
            }
        }
    }
    
    private void updateMoneyLabel(){
        moneyLabel.setText("$" + money);
    }
    
    public void startTimer(){
        Timer timer = new Timer();
        timer.schedule(new GameTick(), 0, 1000);
    }
    
    class GameTick extends TimerTask {
        public void run() {
            tick();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HydroponicsSimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HydroponicsSimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HydroponicsSimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HydroponicsSimulatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HydroponicsSimulatorUI().setVisible(true);
            }
        });    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buyAutoHarvestButton;
    private javax.swing.JButton buyCalciumX2Button;
    private javax.swing.JButton buyMagnesiumX2Button;
    private javax.swing.JButton buyPhosphorusX2Button;
    private javax.swing.JProgressBar calciumBar;
    private javax.swing.JButton calciumButton;
    private javax.swing.JButton harvestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar magnesiumBar;
    private javax.swing.JButton magnesiumButton;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JPanel nutrientBarPanel;
    private javax.swing.JPanel nutrientButtonPanel;
    private javax.swing.JProgressBar phosphorusBar;
    private javax.swing.JButton phosphorusButton;
    private javax.swing.JLabel plant0;
    private javax.swing.JLabel plant1;
    private javax.swing.JLabel plant2;
    private javax.swing.JLabel plant3;
    private javax.swing.JLabel plant4;
    private javax.swing.JButton plantCucumberButton;
    private javax.swing.JLabel plantIcon0;
    private javax.swing.JLabel plantIcon1;
    private javax.swing.JLabel plantIcon2;
    private javax.swing.JLabel plantIcon3;
    private javax.swing.JLabel plantIcon4;
    private javax.swing.JProgressBar plantMaturityBar0;
    private javax.swing.JProgressBar plantMaturityBar1;
    private javax.swing.JProgressBar plantMaturityBar2;
    private javax.swing.JProgressBar plantMaturityBar3;
    private javax.swing.JProgressBar plantMaturityBar4;
    private javax.swing.JButton plantStrawberryButton;
    private javax.swing.JButton plantTomatoButton;
    private javax.swing.JPanel planter0;
    private javax.swing.JPanel planter1;
    private javax.swing.JPanel planter2;
    private javax.swing.JPanel planter3;
    private javax.swing.JPanel planter4;
    private javax.swing.JPanel planterPanel;
    private javax.swing.JPanel purchasePanel;
    // End of variables declaration//GEN-END:variables
    private int money = 25; //Starting money
    ImageIcon stage1Icon = new ImageIcon("assets/stage1.png");
    ImageIcon stage2Icon = new ImageIcon("assets/stage2.png");
    ImageIcon stage3Icon = new ImageIcon("assets/stage3.png");
    int addMagnesium = 5;
    int addPhosphorus = 5;
    int addCalcium = 5;
    boolean autoHarvest = false;
}

